global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: local-services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'local-prometheus:9090'
          - 'idonotexists:564'

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'local-alertmanager:8087' ] 