version: "3.7"
services:
  local-home:
    container_name: local-home
    image: abraham_ntd/local-home:latest
    depends_on:
      - local-db
    build:
      context: .
      dockerfile: containers/home/Dockerfile
    ports:
      - 8080:80
local-apache:
    container_name: local-rest-api
    image: abraham_ntd/local-rest-api:latest
    depends_on:
      - local-db
    build:
      context: .
      dockerfile: containers/api/Dockerfile
    ports:
      - 8081:8080
      - 9091:22
  local-website:
    container_name: local-website
    image: abraham_ntd/local-website:latest
    depends_on:
      - local-db
    build:
      context: .
      dockerfile: containers/web/Dockerfile
    ports:
      - 8082:80
      - 9092:22  
  local-jenkins:
    container_name: local-jenkins
    image: abraham_ntd/local-jenkins:latest
    build:
      context: .
      dockerfile: containers/jenkins/Dockerfile
    environment:
      JENKINS_ADMIN_ID: admin
      JENKINS_ADMIN_PASSWORD: admin
    ports:
      - 8083:8080
      - 9093:50000
  local-sonar:
    container_name: local-sonar
    image: sonarqube:8.9.7-community
    depends_on:
      - local-db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://local-db:5432/sonardb
      SONAR_JDBC_USERNAME: root
      SONAR_JDBC_PASSWORD: admin
    volumes:
      - type: bind
        source: ./volumes/sonarqube/data
        target: /opt/sonarqube/data
      - type: bind
        source: ./volumes/sonarqube/extensions
        target: /opt/sonarqube/extensions
      - type: bind
        source: ./volumes/sonarqube/logs
        target: /opt/sonarqube/logs
    ports:
      - 8084:9000
  init:
      image: bash
      privileged: true
      user: root
      volumes:
        - ./containers/sonar/init.sh:/mnt/init.sh
      command: ["sh", "-e", "/mnt/init.sh"]
  local-pact-broker:
    container_name: local-pact-broker
    image: dius/pact-broker
    ports:
      - 8085:80
    depends_on:
      - local-db
    environment:
      PACT_BROKER_DATABASE_USERNAME: root
      PACT_BROKER_DATABASE_PASSWORD: admin
      PACT_BROKER_DATABASE_HOST: local-db
      PACT_BROKER_DATABASE_NAME: pactbrokerdb
      PACT_BROKER_DATABASE_PORT: 5432
  local-prometheus:
    container_name: local-prometheus
    image: abraham_ntd/local-prometheus:latest
    build:
      context: .
      dockerfile: containers/prometheus/Dockerfile
    ports:
      - 8086:9090
  local-alertmanager:
    container_name: local-alertmanager
    image: prom/alertmanager:v0.23.0
    ports:
      - 8087:9093
  local-grafana:
    container_name: local-grafana
    image: abraham_ntd/local-grafana:latest
    build:
      context: .
      dockerfile: containers/grafana/Dockerfile
    ports:
      - 8088:3000
  local-db:
    container_name: local-db
    image: abraham_ntd/local-db:latest
    build:
      context: .
      dockerfile: containers/postgres/Dockerfile
    healthcheck:
      test: psql postgres --command "select 1"
    volumes:
      - type: bind
        source: ./volumes/postgresql/conf
        target: /var/lib/postgresql
      - type: bind
        source: ./volumes/postgresql/data
        target: /var/lib/postgresql/data