FROM sonarqube:8.9.7-community
LABEL maintainer="agmc22mx@gmail.com"
LABEL description="Sonar server"
LABEL version="1.0"

ENV SONAR_JDBC_URL jdbc:postgresql://local-db:5432/sonardb
ENV SONAR_JDBC_USERNAME root
ENV SONAR_JDBC_PASSWORD admin